version: "3.5"
services:
  mev-boost.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.2.0
    volumes:
      - "data:/var/lib/mev-boost"
    environment:
      NETWORK: ""
      RELAYS: ""
    image: "mev-boost.public.dappnode.eth:0.2.0"
    restart: unless-stopped
volumes:
  data: {}
